### ISSUE TITLE
Federated Networks Association Membership

### ISSUE THREAD

**Issue by extratone** [extratone/extratone#231]
![feneas](https://user-images.githubusercontent.com/43663476/126013509-d806f9a3-f921-4fdb-b250-76b8b5fe5f6b.png)

# "Membership"

*16-07-2021 17:15* 

> Feneas welcomes everybody to join as a member. You don't need to be a developer of a federated project to join.
Feneas welcomes everybody to join as a member. You don't need to be a developer of a federated project to join.

All members are subject to a small membership fee. With these fees we aim to cover costs of not only running the association, but also provide services for the world.

## Why join?

Our mission is to do whatever we can to make the internet a more federated and decentralised place. We believe this is a healthier, more free internet. To do this we need not only funding but also volunteer effort.

The key parts of our mission are:

-   Host federated and decentralized services
-   Provide information about federated web projects
-   Arrange trainings and events
-   Provide travel grants to events
-   Use funds for marketing campaigns to promote federated web projects
-   Use funds to sponsor development work of individuals working on federated web projects or directly donating funds to projects themselves

The usage of every euro will be made public information via monthly financial reports. As a member you get to influence how we spend these funds.

## How to join

As a legal association we keep a member list [as per our rules](https://feneas.git.feneas.org/association/feneas_rules.en.html). We take privacy seriously and will not share the data you have given to us to third parties. Please see our [privacy policy](https://feneas.git.feneas.org/association/privacy_policy.html).

To join as a member, please [fill out the form](https://portal.feneas.org/users/sign_up) and submit it to us.

Alternatively you can also send an email to [hq@feneas.org](mailto:hq@feneas.org) ([PGP Key](https://git.feneas.org/feneas/association/wikis/Assets#pgp)) with the following details:

-   Preferred username (lowercase)
-   Email
-   Full name
-   Domicile (ie country)

Once we process your membership request as per our rules, you will receive an email from our system.

## Annual fee

The annual [kick-off meeting](https://git.feneas.org/feneas/association/wikis/AGM-log-1531945225) verified the annual membership fee to be 1€ per month. The fee is invoiced from users for the whole year in one go, in advance. If a member joins in the middle of the year, they shall pay 1€ per remaining month of the current year, in one go.

Membership fees, as indicated in the rules, are not refundable in any situation. Membership fees can be paid using IBAN bank transfer or by credit card.

### GitLab Ultimate

[GitLab Inc](https://gitlab.com/) has graciously provided the association with a license to help the association provide educational material regarding federated projects. Members have full access to the GitLab server we run. Compare the editions [here](https://about.gitlab.com/pricing/#self-managed).

### Email

Every user gets an automatic `firstname.lastname@feneas.org` email. Currently it will automatically forward to the email given at registration.

### Nextcloud + Collabora account

Our members get a Nextcloud account with the Collabora office suite for their use.

### One vote

All members get one vote in our Annual General Meetings, which are held twice a year. This way you get to shape the direction of our association. Association members are also eligible for positions in the association committee.

### Good feeling

Knowing that you are helping us support the services we provide and making it possible for us to help push the federated web forward.

## I want to help but don't want to be a member

No worries! We also welcome [patreons](https://www.patreon.com/feneas) and [one time donations](https://donorbox.org/feneas).

[![become_a_patron_button](https://feneas.org/content/images/2019/11/become_a_patron_button.png)](https://www.patreon.com/feneas)         [![donorbox](https://feneas.org/content/images/2020/02/donorbox.png)](https://donorbox.org/feneas)
***

==**3070**== Words

- **[Membership](https://feneas.org/membership/)**

**Comment by bkil** [comment]
I think this issue can now be closed
* https://git.feneas.org/feneas/association/-/raw/master/comms/dissolving-the-association-2022-01-09.txt
